spring:
  application:
    name: demo

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always



---
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  sql.init.platform: h2

  datasource:
    url: jdbc:h2:mem:mydb;Mode=Oracle
    driverClassName: org.h2.Driver
  jpa.hibernate.ddl-auto: none